const TEXTS = [

    `Around 80 percent of Greenland is covered by the Greenland Ice Sheet, which Britannica explains is the "largest and possibly the only relic of the Pleistocene glaciations in the Northern Hemisphere." But has it always been so icy? Well, at the bottom of a 1.4 km core sample, which was taken in 1966 at Camp Century during the Cold War, researchers found "well-preserved fossil plants and biomolecules," which means that the massive sheet melted and reformed at least once in the last million years.`
    ,
    `Mount Everest may not have physically grown, having reached maturity a long time ago, however, the most recent measurement performed by surveyors representing China and Nepal has the mountain peak standing taller than we'd thought in the past. Previous readings have ranged from 29,002 feet above sea level in 1856 down to 20,029 in 1955, according to NPR. But after the long process of measuring the mountain with GPS devices, experts have now stated that Mount Everest stands at a whopping 29,031.69 feet, due to plate tectonics.`
    ,
    `When 174 world leaders signed the Paris Agreement on Earth Day in 2016 at the United Nations (UN) headquarters in New York, it was the largest number of countries ever to come together to sign anything on a single day. The agreement aims to combat climate change and accelerate and intensify the actions and investments needed to strengthen the global climate effort.`
    ,
    `You might think you're accustomed to frigid air and blustery winds, but the average winter day has nothing on the coldest day ever recorded, which was -144 degrees Fahrenheit. The temperature was recorded in Antarctica during a span of research between 2004 and 2016. Just a few breaths of air at that temperature would induce hemorrhaging in your lungs and kill you.`
    ,
    `The 1933 Double Eagle was a $20 U.S. coin made of gold that never went into circulation. A few of the coins were made, but most were destroyed-save for nine that were presumed stolen by U.S. mint workers. After years circulating the globe and falling into the hands of a few notable owners-including the king of Egypt-one of the coins was auctioned off at Sotheby's in 2002 for a stunning $7,590,020. That made it the most expensive coin ever sold at auction.`
    ,
    `Few odors are as pleasing as "new car smell"-and not just because it's nice to be in a brand new car. But while the scent may be strangely satisfying, the fact is that it's pretty much just a combination of 50+ chemicals (known as "volatile organic compounds") that are released into the car, decaying quickly over time. The concentrations found in a typical new car aren't dangerous, but among the VOCs that make up much of that new car smell are those found in nail polish, auto fuel, and petroleum.`
    ,
    `Food waste is a huge problem. How big? About 931 million metric tons. That's how much food that researchers with the United Nations estimate was wasted in 2019, according to the Food Waste Index Report 2021, which surveyed 54 countries, finding that the majority of wasted food (61%) comes from homes while restaurants and other food services produce 26% of wasted food. Grocery stores make up just 13% of food waste.`
    ,
    `Pineapples are packed with the enzyme bromelain, which breaks down protein chains, making it an ideal marinade for meats when you don't have a lot of time. But for the same reason, pineapple does not work for jams or jellies, since the enzyme breaks down gelatin as well. The bromelain is so strong that pineapple processors have to wear protective gloves, otherwise over time the enzyme eats away at the skin on their face and hands, leaving dry skin and small sores.`
    ,
    `Science is a systematic endeavor that builds and organizes knowledge in the form of testable explanations and predictions about the universe. Science may be as old as the human species, and some of the earliest archeological evidence for scientific reasoning is tens of thousands of years old. The earliest written records in the history of science come from Ancient Egypt and Mesopotamia in around 3000 to 1200 BCE. Their contributions to mathematics, astronomy, and medicine entered and shaped Greek natural philosophy of classical antiquity, whereby formal attempts were made to provide explanations of events in the physical world based on natural causes. After the fall of the Western Roman Empire, knowledge of Greek conceptions of the world deteriorated in Western Europe during the early centuries (400 to 1000 CE) of the Middle Ages, but was preserved in the Muslim world during the Islamic Golden Age and later by the efforts of Byzantine Greek scholars who brought Greek manuscripts from the dying Byzantine Empire to Western Europe in the Renaissance.`
    ,
    `The recovery and assimilation of Greek works and Islamic inquiries into Western Europe from the 10th to 13th century revived "natural philosophy", which was later transformed by the Scientific Revolution that began in the 16th century as new ideas and discoveries departed from previous Greek conceptions and traditions. The scientific method soon played a greater role in knowledge creation and it was not until the 19th century that many of the institutional and professional features of science began to take shape; along with the changing of "natural philosophy" to "natural science".`
    ,
    `Modern science is typically divided into three major branches: natural sciences (e.g., biology, chemistry, and physics), which study the physical world; the social sciences (e.g., economics, psychology, and sociology), which study individuals and societies; and the formal sciences (e.g., logic, mathematics, and theoretical computer science), which study formal systems, governed by axioms and rules. There is disagreement whether the formal sciences are science disciplines, because they do not rely on empirical evidence. Applied sciences are disciplines that use scientific knowledge for practical purposes, such as in engineering and medicine.`
    ,
    `Game feel (sometimes referred to as "game juice") is the intangible, tactile sensation experienced when interacting with video games. The term was popularized by the book Game Feel: A Game Designer's Guide to Virtual Sensation written by Steve Swink. The term has no formal definition, but there are many defined ways to improve game feel. The different areas of a game that can be manipulated to improve game feel are: input, response, context, aesthetic, metaphor, and rules. Game feel is usually attributed to spatial games whose mechanics involve controlling the movement of objects or characters. Since the majority of games are spatial, studies involving game feel mainly focus on the movement and physical interactions between objects in games. The goal of good game feel is to immerse the player in an engaging and rewarding experience. A way to test game feel is to see if interacting with a game's most basic mechanics feels satisfying. At minimum, the game should feel engaging to play even after the plot, points, level design, music, and graphics are removed; if it is not, then the game may suffer from poor game feel.`
    ,
    `Homo antecessor ('pioneer man') is an archaic human species from 1.2 to 0.8 million years ago during the Early Pleistocene. Fossils have been found in the Sierra de Atapuerca in Spain, the first in 1994. The species was one of the first humans to colonise Western Europe. They followed savanna habitats prevalent in the area when frigid glacial periods were transitioning to warmer interglacials, and vacated at other times. Despite being so ancient, they had a face unexpectedly similar to that of a modern human.`
    ,
    `Imleria is a genus of fungi in the family Boletaceae. It was erected in 2014 by Alfredo Vizzini as a new genus for what had previously been named Boletus badius or Xerocomus badius. It was placed in its own genus because of its distinct morphological features and because it had previously been found to belong in its own genus in a molecular phylogenetics study by Gelardi et al. (2013). Zhu et al. (2014) placed three more species in Imleria. Species of Imleria can be found in Europe, North America and Asia. The genus is named in honor of Belgian mycologist Louis Imler (1900-1993).`
    ,
    `The Nobel Prizes are five separate prizes that, according to Alfred Nobel's will of 1895, are awarded to "those who, during the preceding year, have conferred the greatest benefit to humankind." Alfred Nobel was a Swedish chemist, engineer, and industrialist most famously known for the invention of dynamite. He died in 1896. In his will, he bequeathed all of his "remaining realisable assets" to be used to establish five prizes which became known as "Nobel Prizes." Nobel Prizes were first awarded in 1901.`
    ,
    `Nobel Prizes are awarded in the fields of Physics, Chemistry, Physiology or Medicine, Literature, and Peace (Nobel characterized the Peace Prize as "to the person who has done the most or best to advance fellowship among nations, the abolition or reduction of standing armies, and the establishment and promotion of peace congresses"). In 1968, Sveriges Riksbank (Sweden's central bank) funded the establishment of the Prize in Economic Sciences in Memory of Alfred Nobel, to also be administered by the Nobel Foundation. Nobel Prizes are widely regarded as the most prestigious awards available in their respective fields.`
    ,
    `The Nobel prize ceremonies take place annually. Each recipient (known as a "laureate") receives a gold medal, a diploma, and a monetary award. In 2021, the Nobel Prize monetary award is 10,000,000 SEK. A prize may not be shared among more than three individuals, although the Nobel Peace Prize can be awarded to organizations of more than three people. Although Nobel Prizes are not awarded posthumously, if a person is awarded a prize and dies before receiving it, the prize is presented. The Nobel Prizes, beginning in 1901, and the Nobel Memorial Prize in Economic Sciences, beginning in 1969, have been awarded 609 times to 975 people and 25 organizations. Five individuals and two organisations have received more than one Nobel Prize.`
    ,
    `Alfred Nobel was born on 21 October 1833 in Stockholm, Sweden, into a family of engineers. He was a chemist, engineer, and inventor. In 1894, Nobel purchased the Bofors iron and steel mill, which he made into a major armaments manufacturer. Nobel also invented ballistite. This invention was a precursor to many smokeless military explosives, especially the British smokeless powder cordite. As a consequence of his patent claims, Nobel was eventually involved in a patent infringement lawsuit over cordite. Nobel amassed a fortune during his lifetime, with most of his wealth coming from his 355 inventions, of which dynamite is the most famous.`
    ,
    `Python is a high-level, general-purpose programming language. Its design philosophy emphasizes code readability with the use of significant indentation. Python is dynamically-typed and garbage-collected. It supports multiple programming paradigms, including structured (particularly procedural), object-oriented and functional programming. It is often described as a "batteries included" language due to its comprehensive standard library. Guido van Rossum began working on Python in the late 1980s as a successor to the ABC programming language and first released it in 1991 as Python 0.9.0. Python 2.0 was released in 2000 and introduced new features such as list comprehensions, cycle-detecting garbage collection, reference counting, and Unicode support. Python 3.0, released in 2008, was a major revision that is not completely backward-compatible with earlier versions. Python 2 was discontinued with version 2.7.18 in 2020.. Python consistently ranks as one of the most popular programming languages.`
    ,
    `PHP is a general-purpose scripting language geared toward web development. It was originally created by Danish-Canadian programmer Rasmus Lerdorf in 1993 and released in 1995. The PHP reference implementation is now produced by The PHP Group. PHP originally stood for Personal Home Page, but it now stands for the recursive initialism PHP: Hypertext Preprocessor. PHP code is usually processed on a web server by a PHP interpreter implemented as a module, a daemon or as a Common Gateway Interface (CGI) executable.`
    ,
    `The carrot (Daucus carota subsp. sativus) is a root vegetable, typically orange in color, though purple, black, red, white, and yellow cultivars exist, all of which are domesticated forms of the wild carrot, Daucus carota, native to Europe and Southwestern Asia. The plant probably originated in Persia and was originally cultivated for its leaves and seeds. The most commonly eaten part of the plant is the taproot, although the stems and leaves are also eaten. The domestic carrot has been selectively bred for its enlarged, more palatable, less woody-textured taproot.`
    ,
    `A cherry is the fruit of many plants of the genus Prunus, and is a fleshy drupe (stone fruit). Commercial cherries are obtained from cultivars of several species, such as the sweet Prunus avium and the sour Prunus cerasus. The name 'cherry' also refers to the cherry tree and its wood, and is sometimes applied to almonds and visually similar flowering trees in the genus Prunus, as in "ornamental cherry" or "cherry blossom". Wild cherry may refer to any of the cherry species growing outside cultivation, although Prunus avium is often referred to specifically by the name "wild cherry" in the British Isles.`
    ,
    `Blueberries are a widely distributed and widespread group of perennial flowering plants with blue or purple berries. They are classified in the section Cyanococcus within the genus Vaccinium. Vaccinium also includes cranberries, bilberries, huckleberries and Madeira blueberries. Commercial blueberries-both wild (lowbush) and cultivated (highbush)-are all native to North America. The highbush varieties were introduced into Europe during the 1930s. Blueberries are usually prostrate shrubs that can vary in size from 10 centimeters (4 inches) to 4 meters (13 feet) in height. In commercial production of blueberries, the species with small, pea-size berries growing on low-level bushes are known as "lowbush blueberries" (synonymous with "wild"), while the species with larger berries growing on taller, cultivated bushes are known as "highbush blueberries". Canada is the leading producer of lowbush blueberries, while the United States produces some 40% of the world supply of highbush blueberries.`
    ,
    `Mosquitoes (or mosquitos) are members of a group of almost 3,600 species of small flies within the family Culicidae (from the Latin culex meaning "gnat"). The word "mosquito" (formed by mosca and diminutive -ito) is Spanish for "little fly". Mosquitoes have a slender segmented body, one pair of wings, one pair of halteres, three pairs of long hair-like legs, and elongated mouthparts.The mosquito life cycle consists of egg, larva, pupa, and adult stages. Eggs are laid on the water surface; they hatch into motile larvae that feed on aquatic algae and organic material. These larvae are important food sources for many freshwater animals, such as dragonfly nymphs, many fish, and some birds such as ducks. The adult females of most species have tube-like mouthparts (called a proboscis) that can pierce the skin of a host and feed on blood, which contains protein and iron needed to produce eggs. Thousands of mosquito species feed on the blood of various hosts - vertebrates, including mammals, birds, reptiles, amphibians, and some fish; along with some invertebrates, primarily other arthropods.`
    ,
    `The mosquito's saliva is transferred to the host during the bite, and can cause an itchy rash. In addition, many species can ingest pathogens while biting, and transmit them to future hosts. In this way, mosquitoes are important vectors of parasitic diseases such as malaria and filariasis, and arboviral diseases such as yellow fever, Chikungunya, West Nile, dengue fever, and Zika. By transmitting diseases, mosquitoes cause the deaths of more people than any other animal taxon: over 700,000 each year. It has been claimed that almost half of the people who have ever lived have died of mosquito-vectored disease, but this claim is disputed, with more conservative estimates placing the death toll closer to 5% of all humans. Mosquitoes cannot live or function properly when the air temperature is below 10 degrees Celsius (50 degrees Fahrenheit). They are mostly active at 15-25 degrees Celsius (60-80 degrees Fahrenheit).`
    ,
    `Leprosy, also known as Hansen's disease (HD), is a long-term infection by the bacteria Mycobacterium leprae or Mycobacterium lepromatosis. Infection can lead to damage of the nerves, respiratory tract, skin, and eyes. This nerve damage may result in a lack of ability to feel pain, which can lead to the loss of parts of a person's extremities from repeated injuries or infection through unnoticed wounds. An infected person may also experience muscle weakness and poor eyesight. Leprosy symptoms may begin within one year, but, for some people, symptoms may take 20 years or more to occur.`
    ,
    `Some things are under my control, while others are not. Under my control are conception, choice, desire, aversion, and, in a word, everything that is my own doing. Not under my control are my body, my property, reputation, office, and, in a word, everything that is not my own doing. Furthermore, the things under my control are by nature free, unhindered, and unimpeded; while the things not under my control are weak, servile, subject to hindrance, and not my own. As a result, if I consider something slavish to be free, and what is not my own to be my own, I will be hampered, will grieve, will be in turmoil, and will blame everything and everybody. Therefore, I will consider only what is my own to be my own, and what is not my own to be not my own, then no one will ever be able to exert compulsion upon me, no one will hinder me, I will blame no one, will find fault with no one, will do absolutely nothing against my will, I will have no personal enemy, no one will harm me, for neither is there any harm that can touch me.`
    ,
    `Following my desire promises the attainment of what I am desirous; and aversion promises the avoidance of what I am averse. However, the one who fails to obtain the object of ones desire is disappointed, and the one who incurs the object of ones aversion wretched. Therefore, I will remove aversion from all things that are not under my control, including sickness and death, to not clutter my mind with useless thoughts, and transfer it to what is under my very control, so I can undertake actions to get rid of those things effectively. I will totally suppress desire, for, when I desire any of the things which are not in my own control, I must necessarily be disappointed; and of those which are under my control, nothing is yet in my possession. I will only use the appropriate actions of pursuit and avoidance; and even these lightly, and with gentleness and reservation.`
    ,
    `Mastery is about skill and technique. The only way to achieve it, is deliberate practice. Deliberate practice is not simply performing a task. If I ask myself, "Why am I performing this task?" and the answer is, "To complete the task," then it is not deliberate practice. Deliberate practice does not mean doing what I am good at; it means challenging myself and doing what I am not good at to achieve my goal. Deliberate practice means repetition. It means performing a task with the aim of improving my skill within one or more aspects of that task. It means repeating the repetition. Slowly, over and over again, until it becomes second nature to me. Greatness is not the result of an innate ability but largely a matter of conscious choice. My choice!`
    ,
    `I must keep in mind that it is not the things themselves that disturb me, but my very own judgments about these things! For example, death is nothing dreadful, it is a natural part of life, just as birth is, but the judgment that death is dreadful - this alone is the dreadful thing. When, therefore, I am hindered, or disturbed, or grieved, I will never blame anyone, nor myself, but only my particular judgment of a particular situation. Since my judgment originates in my mind, I have full control over it and, thus, can change it easily. It is a characteristic of an uneducated person to blame others where that person fares ill. One who blames one's self is a person whose education has just begun. To blame neither another nor one's own self is part of a person whose education is already complete - this person I shall become.`
    ,
    `When I see someone crying in grief because his or her loved one has gone abroad, or is dead, or because he or she has suffered in his or her affairs, I must be careful that the appearance does not fool me. Instead, I will distinguish within my own mind, and be prepared to say: "It's not the accident that distresses this person, because it doesn't distress another person; it is the judgment which that particular person makes about it." It is ok for me to sympathize with him so far as words go, and, if occasion offers, even to groan with him; but I will be careful to keep this groan on the very surface of my being and won't let it any deeper to clutter my mind.`
    ,
    `Body mass index (BMI) is a value derived from the mass (weight) and height of a person. The BMI is defined as the body mass divided by the square of the body height, and is expressed in units of kg/m2, resulting from mass in kilograms and height in metres. The BMI may be determined using a table or chart which displays BMI as a function of mass and height using contour lines or colours for different BMI categories, and which may use other units of measurement (converted to metric units for the calculation). The BMI is a convenient rule of thumb used to broadly categorize a person as underweight, normal weight, overweight, or obese based on tissue mass (muscle, fat, and bone) and height. Major adult BMI classifications are underweight (under 18.5 kg/m2), normal weight (18.5 to 24.9), overweight (25 to 29.9), and obese (30 or more). BMIs under 20 and over 25 have been associated with higher all-cause mortality.`
    ,
    `Linux was originally developed for personal computers based on the Intel x86 architecture, but has since been ported to more platforms than any other operating system. Because of the dominance of the Linux-based Android on smartphones, Linux, including Android, has the largest installed base of all general-purpose operating systems, as of May 2022. Although Linux is, as of November 2022, used by only around 2.6 percent of desktop computers, the Chromebook, which runs the Linux kernel-based Chrome OS, dominates the US K-12 education market and represents nearly 20 percent of sub-$300 notebook sales in the US. Linux is the leading operating system on servers (over 96.4% of the top 1 million web servers' operating systems are Linux), leads other big iron systems such as mainframe computers, and is the only OS used on TOP500 supercomputers (since November 2017, having gradually eliminated all competitors).`
    ,
    `pen-source software (OSS) is computer software that is released under a license in which the copyright holder grants users the rights to use, study, change, and distribute the software and its source code to anyone and for any purpose. Open-source software may be developed in a collaborative public manner. Open-source software is a prominent example of open collaboration, meaning any capable user is able to participate online in development, making the number of possible contributors indefinite. The ability to examine the code facilitates public trust in the software.`
    ,
    `A characteristic that places fungi in a different kingdom from plants, bacteria, and some protists is chitin in their cell walls. Fungi, like animals, are heterotrophs; they acquire their food by absorbing dissolved molecules, typically by secreting digestive enzymes into their environment. Fungi do not photosynthesize. Growth is their means of mobility, except for spores (a few of which are flagellated), which may travel through the air or water. Fungi are the principal decomposers in ecological systems. These and other differences place fungi in a single group of related organisms, named the Eumycota (true fungi or Eumycetes), that share a common ancestor (i.e. they form a monophyletic group), an interpretation that is also strongly supported by molecular phylogenetics. This fungal group is distinct from the structurally similar myxomycetes (slime molds) and oomycetes (water molds). The discipline of biology devoted to the study of fungi is known as mycology.`
    ,
    `The guinea pig or domestic guinea pig (Cavia porcellus), also known as the cavy or domestic cavy, is a species of rodent belonging to the genus Cavia in the family Caviidae. Breeders tend to use the word cavy to describe the animal, while in scientific and laboratory contexts, it is far more commonly referred to by the common name guinea pig. Despite their common name, guinea pigs are not native to Guinea, nor are they closely related biologically to pigs, and the origin of the name is still unclear. They originated in the Andes of South America. Studies based on biochemistry and hybridization suggest they are domesticated animals that do not exist naturally in the wild, descendants of a closely related cavy species such as C. tschudii. They were originally domesticated as livestock for a source of meat, and are still consumed in some parts of the world.`
    ,
    `A dictatorship is a form of government which is characterized by a leader or a group of leaders which holds governmental powers with few to no limitations on them. The leader of a dictatorship is called a dictator. Politics in a dictatorship take place between the dictator, the inner circle, and the opposition, which may be peaceful or violent. Dictatorships can be formed by a military coup that overthrows the previous government through force or by a self-coup in which elected leaders make their rule permanent. Dictatorships are authoritarian or totalitarian and can be classified as military dictatorships, one-party dictatorships, personalist dictatorships, or absolute monarchies.`
    ,
    `An integrated circuit or monolithic integrated circuit (also referred to as an IC, a chip, or a microchip) is a set of electronic circuits on one small flat piece (or "chip") of semiconductor material, usually silicon. Large numbers of tiny MOSFETs (metal-oxide-semiconductor field-effect transistors) integrate into a small chip. This results in circuits that are orders of magnitude smaller, faster, and less expensive than those constructed of discrete electronic components. The IC's mass production capability, reliability, and building-block approach to integrated circuit design has ensured the rapid adoption of standardized ICs in place of designs using discrete transistors. ICs are now used in virtually all electronic equipment and have revolutionized the world of electronics. Computers, mobile phones and other home appliances are now inextricable parts of the structure of modern societies, made possible by the small size and low cost of ICs such as modern computer processors and microcontrollers.`
    ,
    `A white dwarf is a stellar core remnant composed mostly of electron-degenerate matter. A white dwarf is very dense: its mass is comparable to the Sun's, while its volume is comparable to the Earth's. A white dwarf's faint luminosity comes from the emission of residual thermal energy; no fusion takes place in a white dwarf. The nearest known white dwarf is Sirius B, at 8.6 light years, the smaller component of the Sirius binary star. There are currently thought to be eight white dwarfs among the hundred star systems nearest the Sun. The unusual faintness of white dwarfs was first recognized in 1910. The name white dwarf was coined by Willem Luyten in 1922. White dwarfs are thought to be the final evolutionary state of stars whose mass is not high enough to become a neutron star or black hole. This includes over 97% of the other stars in the Milky Way.`
    ,
    `A red dwarf is the smallest and coolest kind of star on the main sequence. Red dwarfs are by far the most common type of star in the Milky Way, at least in the neighborhood of the Sun, but because of their low luminosity, individual red dwarfs cannot be easily observed. From Earth, not one star that fits the stricter definitions of a red dwarf is visible to the naked eye. Proxima Centauri, the nearest star to the Sun, is a red dwarf, as are fifty of the sixty nearest stars. According to some estimates, red dwarfs make up three-quarters of the stars in the Milky Way. The coolest red dwarfs near the Sun have a surface temperature of about 2,000 K and the smallest have radii about 9% that of the Sun, with masses about 7.5% that of the Sun.`
    ,
    `A pulsar (from pulsating radio source) is a highly magnetized rotating neutron star that emits beams of electromagnetic radiation out of its magnetic poles. This radiation can be observed only when a beam of emission is pointing toward Earth (similar to the way a lighthouse can be seen only when the light is pointed in the direction of an observer), and is responsible for the pulsed appearance of emission. Neutron stars are very dense and have short, regular rotational periods. This produces a very precise interval between pulses that ranges from milliseconds to seconds for an individual pulsar. Pulsars are one of the candidates for the source of ultra-high-energy cosmic rays.`
    ,
    `Dark matter is a hypothetical form of matter thought to account for approximately 85% of the matter in the universe. Dark matter is called "dark" because it does not appear to interact with the electromagnetic field, which means it does not absorb, reflect, or emit electromagnetic radiation and is, therefore, difficult to detect. Various astrophysical observations - including gravitational effects which cannot be explained by currently accepted theories of gravity unless more matter is present than can be seen - imply dark matter's presence. For this reason, most experts think that dark matter is abundant in the universe and has had a strong influence on its structure and evolution.. The primary evidence for dark matter comes from calculations showing that many galaxies would behave quite differently if they did not contain a large amount of unseen matter. Some galaxies would not have formed at all and others would not move as they currently do.`
    ,
    `A virus is a submicroscopic infectious agent that replicates only inside the living cells of an organism. Viruses infect all life forms, from animals and plants to microorganisms, including bacteria and archaea. Since Dmitri Ivanovsky's 1892 article describing a non-bacterial pathogen infecting tobacco plants and the discovery of the tobacco mosaic virus by Martinus Beijerinck in 1898, more than 9,000 virus species have been described in detail of the millions of types of viruses in the environment. Viruses are found in almost every ecosystem on Earth and are the most numerous type of biological entity. The study of viruses is known as virology, a subspeciality of microbiology.`
    ,
    `Cockroaches (or roaches) are a paraphyletic group of insects belonging to Blattodea, containing all members of the group except termites. About 30 cockroach species out of 4,600 are associated with human habitats. Some species are well-known as pests. The cockroaches are an ancient group, with their ancestors, known as "roachoids", originating during the Carboniferous period, some 320 million years ago. Those early ancestors, however, lacked the internal ovipositors of modern roaches. Cockroaches are somewhat generalized insects lacking special adaptations (such as the sucking mouthparts of aphids and other true bugs); they have chewing mouthparts and are probably among the most primitive of living Neopteran insects. They are common and hardy insects capable of tolerating a wide range of climates, from Arctic cold to tropical heat.`
    ,
    `Malaria is caused by single-celled microorganisms of the Plasmodium group. It is spread exclusively through bites of infected Anopheles mosquitoes. The mosquito bite introduces the parasites from the mosquito's saliva into a person's blood. The parasites travel to the liver where they mature and reproduce. Five species of Plasmodium can infect and be spread by humans. Most deaths are caused by P. falciparum, whereas P. vivax, P. ovale, and P. malariae generally cause a milder form of malaria. The species P. knowlesi rarely causes disease in humans. Malaria is typically diagnosed by the microscopic examination of blood using blood films, or with antigen-based rapid diagnostic tests. Methods that use the polymerase chain reaction to detect the parasite's DNA have been developed, but are not widely used in areas where malaria is common due to their cost and complexity.`
    ,
    `An android is a humanoid robot or other artificial being often made from a flesh-like material. Historically, androids were completely within the domain of science fiction and frequently seen in film and television, but recent advances in robot technology now allow the design of functional and realistic humanoid robots. While the term "android" is used in reference to human-looking robots in general (not necessarily male-looking humanoid robots), a robot with a female appearance can also be referred to as a gynoid. Besides one can refer to robots without alluding to their sexual appearance by calling them anthrobots (merging the radical anthrōpos and the word robot; see anthrobotics) or anthropoids (short for anthropoid robots; the term humanoids is not appropriate because it is already commonly used to refer to human-like organic species in the context of scientific fiction, futurism and speculative astrobiology).`
    ,
    `A neutron star is the collapsed core of a massive supergiant star, which had a total mass of between 10 and 25 solar masses, possibly more if the star was especially metal-rich. Except for black holes and some hypothetical objects (e.g. white holes, quark stars, and strange stars), neutron stars are the smallest and densest currently known class of stellar objects. Neutron stars have a radius on the order of 10 kilometres (6 mi) and a mass of about 1.4 solar masses. They result from the supernova explosion of a massive star, combined with gravitational collapse, that compresses the core past white dwarf star density to that of atomic nuclei. Once formed, they no longer actively generate heat, and cool over time; however, they may still evolve further through collision or accretion.`
    ,
    `The Amazon rainforest, Amazon jungle or Amazonia is a moist broadleaf tropical rainforest in the Amazon biome that covers most of the Amazon basin of South America. This basin encompasses 7,000,000 km2 (2,700,000 sq mi), of which 5,500,000 km2 (2,100,000 sq mi) are covered by the rainforest. This region includes territory belonging to nine nations and 3,344 formally acknowledged indigenous territories. The majority of the forest is contained within Brazil, with 60% of the rainforest, followed by Peru with 13%, Colombia with 10%, and with minor amounts in Bolivia, Ecuador, French Guiana, Guyana, Suriname, and Venezuela.`
    ,
    `The Great Wall of China is a series of fortifications that were built across the historical northern borders of ancient Chinese states and Imperial China as protection against various nomadic groups from the Eurasian Steppe. Several walls were built from as early as the 7th century BC, with selective stretches later joined by Qin Shi Huang (220-206 BC), the first emperor of China. Little of the Qin wall remains. Later on, many successive dynasties built and maintained multiple stretches of border walls. The best-known sections of the wall were built by the Ming dynasty (1368-1644).`
    ,
    `A mitochondrion is a double-membrane-bound organelle found in most eukaryotic organisms. Mitochondria use aerobic respiration to generate most of the cell's supply of adenosine triphosphate (ATP), which is subsequently used throughout the cell as a source of chemical energy. They were discovered by Albert von Kölliker in 1857 in the voluntary muscles of insects. The term mitochondrion was coined by Carl Benda in 1898. The mitochondrion is popularly nicknamed the "powerhouse of the cell", a phrase coined by Philip Siekevitz in a 1957 article of the same name.`
    ,
    `Deoxyribonucleic acid (DNA) is a polymer composed of two polynucleotide chains that coil around each other to form a double helix carrying genetic instructions for the development, functioning, growth and reproduction of all known organisms and many viruses. DNA and ribonucleic acid (RNA) are nucleic acids. Alongside proteins, lipids and complex carbohydrates (polysaccharides), nucleic acids are one of the four major types of macromolecules that are essential for all known forms of life. The two DNA strands are known as polynucleotides as they are composed of simpler monomeric units called nucleotides. Each nucleotide is composed of one of four nitrogen-containing nucleobases (cytosine, guanine, adenine or thymine), a sugar called deoxyribose, and a phosphate group.`
    ,
    `The Poor Fellow-Soldiers of Christ and of the Temple of Solomon (Latin: Pauperes commilitones Christi Templique Salomonici), also known as the Order of Solomon's Temple, the Knights Templar, or simply the Templars, was a Catholic military order, one of the most wealthy and popular of the Western Christian military orders. They were founded in 1119, headquartered on the Temple Mount in Jerusalem, and existed for nearly two centuries during the Middle Ages. Officially endorsed by the Roman Catholic Church by such decrees as the papal bull Omne datum optimum of Pope Innocent II, the Templars became a favored charity throughout Christendom and grew rapidly in membership and power.`
    ,
    `In Greek mythology, Andromeda is the daughter of Cepheus and Cassiopeia, king and queen of ancient Ethiopia. Her mother Cassiopeia foolishly boasts that she is more beautiful than the Nereids, a display of hubris by a human that is unacceptable to the gods. To punish the queen for her arrogance, Poseidon floods the Ethiopian coast and sends a sea monster named Cetus to ravage the kingdom's inhabitants. In desperation, King Cepheus consults the oracle of Ammon, who announces that no respite can be found until the king sacrifices his daughter, Andromeda, to the monster. She is thus chained to a rock by the sea to await her death.`
    ,
    `Perseus is just then flying near the coast of Ethiopia on his winged sandals, having slain the Gorgon Medusa and carrying her severed head, which instantly turns to stone any who look at it. Upon seeing Andromeda bound to the rock, Perseus falls in love with her, and he secures Cepheus' promise of her hand in marriage if he can save her. Perseus kills the monster with the magical sword he had used against Medusa, saving Andromeda. Preparations are then made for their marriage, in spite of her having been previously promised to her uncle, Phineus. At the wedding, a quarrel between the rivals ends when Perseus shows Medusa's head to Phineus and his allies, turning them to stone.`
    ,
    `Jupiter is primarily composed of hydrogen, but helium constitutes one-quarter of its mass and one-tenth of its volume. It probably has a rocky core of heavier elements, but, like the other giant planets in the Solar System, it lacks a well-defined solid surface. The ongoing contraction of Jupiter's interior generates more heat than it receives from the Sun. Because of its rapid rotation, the planet's shape is an oblate spheroid: it has a slight but noticeable bulge around the equator. The outer atmosphere is divided into a series of latitudinal bands, with turbulence and storms along their interacting boundaries. A prominent result of this is the Great Red Spot, a giant storm which has been observed since at least 1831.`
    ,

]